version: '3'
services:
  robot:
    image: jeguzzi/thymio:humble
    network_mode: &net host
    pid: &pid host
    privileged: true
    restart: always
    command: ros2 launch thymio_driver mt_base.launch
    env_file:
      - ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
      - ./ros2_launch/humble/mt_base.launch:/opt/ros/humble/share/thymio_driver/launch/mt_base.launch:ro
      - ./ros2_launch/humble/motor.yaml:/opt/ros/humble/share/thymio_driver/launch/motor.yaml:ro
  state:
    image: jeguzzi/thymioid:humble
    network_mode: *net
    pid: *pid
    command: ros2 launch thymioid mt_state.launch
    restart: always
    env_file:
      - ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
      - ./ros2_launch/humble/mt_state.launch:/opt/ros/humble/share/thymioid/launch/mt_state.launch:ro
  camera:
    image: jeguzzi/mt-camera:humble
    network_mode: *net
    pid: *pid
    privileged: true
    command: ros2 launch v4l2_camera camera.launch
    restart: always
    env_file:
      - ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
      - ./ros2_launch/humble/camera.yaml:/root/.ros/camera_info/usb_2.0_camera.yaml:ro
      - ./ros2_launch/humble/camera.launch:/opt/ros/humble/share/v4l2_camera/launch/camera.launch:ro
  ups:
    image: jeguzzi/mt-ups:humble
    network_mode: *net
    pid: *pid
    privileged: true
    command: ros2 launch odroid_ups mt_ups.launch
    restart: always
    env_file:
      - ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
      - ./ros2_launch/humble/mt_ups.launch:/opt/ros/humble/share/odroid_ups/launch/mt_ups.launch:ro
  ui:
    image: jeguzzi/thymioid:humble
    network_mode: *net
    pid: *pid
    command: ros2 launch thymioid mt_ui.launch
    restart: always
    env_file:
      - ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
      - ./ros2_launch/humble/mt_ui.launch:/opt/ros/humble/share/thymioid/launch/mt_ui.launch:ro
      - /run/network/ifstate.wlan0:/run/network/ifstate.wlan0
      - /root/docker/mighty-thymio/wlan:/wlan:rw
      - /root/docker/mighty-thymio/shutdown:/shutdown:rw
      - /root/docker/mighty-thymio/update:/update:rw
    depends_on:
      - robot
  teleop:
    image: jeguzzi/mt-teleop:humble
    network_mode: *net
    pid: *pid
    privileged: true
    command: ros2 launch thymioid mt_teleop.launch
    restart: always
    env_file:
      - ros.env
    volumes:
      - ./logs:/root/.ros/log:rw
      - ./ros2_launch/humble/mt_teleop.launch:/opt/ros/humble/share/thymioid/launch/mt_teleop.launch:ro
      - ./ros2_launch/humble/joy_config.yaml:/opt/ros/humble/share/thymioid/configuration/joy_config.yaml:ro
    depends_on:
      - robot
  portainer:
    command: --no-auth
    image: portainer/portainer
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
